version: "3"

services:
  mongodb-container:
    image: mongo:latest
    container_name: "mongodb-container"
    restart: always
    ports:
      - 27017:27017
  server-container:
    image: server_side
    container_name: "server-container"
    restart: always
    ports:
      - 5003:5003
    links:
      - mongodb-container
    depends_on:
      - mongodb-container